In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('per.csv')
data.head()

NewsID                                              Title  \
0  843656  \nوزير علوم درجمع استادان نمونه: سن بازنشستگي ...   
1  837144  \nگردهمايي دانش‌آموختگان موسسه آموزش عالي سوره...   
2  436862  \nنتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌نور...   
3  227781  \nهمايش يكروزه آسيب شناسي مفهوم روابط عمومي در...   
4  174187  \nوضعيت اقتصادي و ميزان تحصيلات والدين از مهمت...   

                                                Body         Date       Time  \
0  \nوزير علوم در جمع استادان نمونه كشور گفت: از ...  \n138/5//09  \n0:9::18   
1  \nبه گزارش سرويس صنفي آموزشي خبرگزاري دانشجويا...  \n138/5//09  \n1:4::11   
2  \nنتايج آزمون دوره‌هاي فراگير مقاطع كارشناسي و...  \n138/3//07  \n1:0::03   
3                                                 \n  \n138/2//02  \n1:3::42   
4  \nمحمدتقي علوي يزدي، مجري اين طرح پژوهشي در اي...  \n138/1//08  \n1:1::49   

             Category  Category2  
0           \nآموزشي-   \nآموزشي  
1           \nآموزشي-   \nآموزشي  
2           \nآموزشي-   \nآموزشي  
3  \nاجتماعي-خانواده-  \nاجتماعي  
4           \nآموزشي-   \nآموزشي

In [7]:
with open('stopwords.txt', 'r', encoding='utf8') as stopwords_file:
    stopwords = stopwords_file.readlines()
stopwords = [line.replace('\n', '') for line in stopwords]
stopwords

['!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '...',
 '....',
 '/',
 ':',
 '<',
 '=',
 '>',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 '{',
 '|',
 '}',
 '~',
 '«',
 '»',
 '،',
 '؛',
 '؟',
 'ء',
 'آاو و و و',
 'آباد',
 'آخ',
 'آخر',
 'آخرها',
 'آخه',
 'آدمهاست',
 'آرام',
 'آرام آرام',
 'آره',
 'آری',
 'آزادانه',
 'آسان',
 'آسانی',
 'آسيب پذيرند',
 'آسیب',
 'آسیب پذیرند',
 'آشكارا',
 'آشنايند',
 'آشنایند',
 'آشکارا',
 'آقا',
 'آقای',
 'آقایان',
 'آمد',
 'آمدن',
 'آمده',
 'آمرانه',
 'آن',
 'آن ها',
 'آن گاه',
 'آنان',
 'آناني',
 'آنانی',
 'آنجا',
 'آنرا',
 'آنطور',
 'آنقدر',
 'آنكه',
 'آنها',
 'آنهاست',
 'آنچنان',
 'آنچنان كه',
 'آنچنان که',
 'آنچه',
 'آنکه',
 'آنگاه',
 'آن\u200cها',
 'آهان',
 'آهاي',
 'آهای',
 'آور',
 'آورد',
 'آوردن',
 'آورده',
 'آوه',
 'آيا',
 'آيد',
 'آی',
 'آیا',
 'آید',
 'آیند',
 'ا',
 'ابدا',
 'ابلهانه',
 'ات',
 'اتفاقا',
 'اثر',
 'اثرِ',
 'اجراست',
 'احتراما',
 'احتمالا',
 'احياناً',
 'احیانا',
 'احیاناً',
 'اخ',
 'اختصارا',

In [8]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\kavia\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [9]:
nltk_stopwords = nltk.corpus.stopwords.words('english')
stopwords.extend(nltk_stopwords)
len(stopwords)

2976

In [10]:
import hazm
stemmer = hazm.Stemmer()

In [11]:
stemmer.stem('استادها')

'استاد'

In [12]:
lem = hazm.Lemmatizer()

In [13]:
lem.lemmatize('می‌آییم')

'آمد#آ'

In [14]:
from hazm import word_tokenize

In [15]:
r = data.iloc[0]
r = r['Title'] + r['Body']
r

'\nوزير علوم درجمع استادان نمونه: سن بازنشستگي استادان نمونه به 70 سال افزايش مي\u200cيابد دانشگاه بايد مهد چالشهاي گفتماني و خط دهنده و برنامه\u200cريز جريانات سياسي باشد\nوزير علوم در جمع استادان نمونه كشور گفت: از استادان نمونه كشور انتظار مي\u200cرود كه رويكرد دانايي محوري و گفتمان علمي را به عنوان يك بحث فرهنگي در دانشگاهها توسعه و رونق بخشند. به گزارش سرويس صنفي آموزشي خبرگزاري دانشجويان ايران (ايسنا)، دكتر محمد مهدي زاهدي در اولين مجمع عمومي استادان نمونه دانشگاه\u200cهاي سراسر كشور كه در دانشگاه تهران برگزار شد، افزود: توصيه ما در جهت تلاش براي دانايي محوري و توسعه گفتمان علمي به معني عدم تمايل به مباحث سياسي نيست؛ بلكه برعكس، دانشگاه بايد مهد چالشهاي گفتماني باشد ولي اين امر، بدان معني نيست كه دانشگاه، ابزار دست سياسيون قرار بگيرد. وي تأكيد كرد: دانشگاه نه تنها نبايد تحت تأثير القائات سياسي قرار بگيرد؛ بلكه بايد خط دهنده و برنامه\u200cريز جريانات سياسي باشد و مهمترين عنصر پياده شدن اين آرمان، دانشجويان و اعضاي هيات علمي دانشگاهها و در رأس آنها استادان نمونه هستند. وزير علوم با

In [16]:
r = data.iloc[0]
r = r['Title'] + r['Body']
title_body_tokenized = word_tokenize(r)
title_body_tokenized_filtered = [w for w in title_body_tokenized if not w in stopwords]
title_body_tokenized_filtered_stemmed = [stemmer.stem(w) for w in title_body_tokenized_filtered]
title_body_tokenized_filtered_lem = [lem.lemmatize(w).replace('#', ' ') for w in title_body_tokenized_filtered]
' '.join(title_body_tokenized_filtered_lem) + ' ' + ' '.join(title_body_tokenized_filtered_stemmed)

'وزير علوم درجمع استاد نمونه سن بازنشستگي استاد نمونه 70 افزايش مي\u200cيابد دانشگاه مهد چالشهاي گفتماني خط دهنده برنامه\u200cريز جريانات سياسي وزير علوم استاد نمونه كشور استاد نمونه كشور انتظار مي\u200cرود رويكرد دانايي محوري گفتمان علمي بحث فرهنگي دانشگاه توسعه رونق بخشید بخش گزارش سرويس صنفي آموزشي خبرگزاري دانشجويان ايران ايسنا دكتر محمد مهدي زاهدي اولين مجمع عمومي استاد نمونه دانشگاه\u200cهاي كشور دانشگاه تهران برگزار توصيه تلاش دانايي محوري توسعه گفتمان علمي معني تمايل مباحث سياسي دانشگاه مهد چالشهاي گفتماني امر معني دانشگاه ابزار دست سياسيون بگيرد تأكيد دانشگاه تأثير القائات سياسي بگيرد خط دهنده برنامه\u200cريز جريانات سياسي مهمترين عنصر پياده آرمان دانشجويان اعضاي هيات علمي دانشگاه رأس استاد نمونه وزير علوم ذكر نكته جامعه اطلاعاتي نمي\u200cتوان تفكري تهديد ارعاب حاكم دانشگاه پرچمدار كرسيهاي آزاد انديشي حاكميت دانايي محوري توجه داشت دار ناخودآگاه تأثير جوسازيها القائات رسانه نگيرند دكتر زاهدي اقدامات ارتقاي جايگاه استاد نمونه اشاره بنياد نخبگان استاد نمونه مصاديق نخبگان شناخت شن

In [17]:
dataset = pd.DataFrame(columns=('title_body', 'category'))
for index, row in data.iterrows():
    title_body = row['Title'] + ' ' + row['Body']
    title_body_tokenized = word_tokenize(title_body)
    title_body_tokenized_filtered = [w for w in title_body_tokenized if not w in stopwords]
    title_body_tokenized_filtered_stemmed = [stemmer.stem(w) for w in title_body_tokenized_filtered]
    title_body_tokenized_filtered_lem = [lem.lemmatize(w).replace('#', ' ') for w in title_body_tokenized_filtered]
    dataset.loc[index] = {
        'title_body': ' '.join(title_body_tokenized_filtered_lem) + ' ' + ' '.join(title_body_tokenized_filtered_stemmed),
        'category': row['Category2'].replace('\n', '')
    }

In [18]:
dataset.head()

title_body category
0  وزير علوم درجمع استاد نمونه سن بازنشستگي استاد...   آموزشي
1  گردهمايي دانش‌آموختگان موسسه آموزش عالي سوره ب...   آموزشي
2  نتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌نور ن...   آموزشي
3  همايش يكروزه آسيب مفهوم روابط عمومي بابلسر برگ...  اجتماعي
4  وضعيت اقتصادي تحصيلات والدين مهمترين عوامل موف...   آموزشي

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [20]:
vectorizer = TfidfVectorizer(ngram_range=(1, 2))
vectorizer.fit(dataset['title_body'])

TfidfVectorizer(ngram_range=(1, 2))

In [21]:
X = vectorizer.transform(dataset['title_body'])

In [22]:
X

<10999x1852205 sparse matrix of type '<class 'numpy.float64'>'
	with 5335417 stored elements in Compressed Sparse Row format>

In [23]:
from sklearn.preprocessing import LabelEncoder

In [24]:
le = LabelEncoder()
y = le.fit_transform(dataset['category'])

In [25]:
le.classes_

array(['آموزشي', 'اجتماعي', 'اقتصادي', 'بهداشتي', 'تاريخي', 'سياسي',
       'علمي', 'فرهنگي', 'فقه و حقوق', 'مذهبي', 'ورزشي'], dtype=object)

In [26]:
len(y)

10999

In [27]:
import numpy as np
print(np.unique(dataset['category']))

['آموزشي' 'اجتماعي' 'اقتصادي' 'بهداشتي' 'تاريخي' 'سياسي' 'علمي' 'فرهنگي'
 'فقه و حقوق' 'مذهبي' 'ورزشي']


In [28]:
np.shape(X)

(10999, 1852205)

In [29]:
np.shape(y)

(10999,)

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [32]:
from sklearn import svm

In [33]:
svmc = svm.SVC()
svmc.fit(X_train, y_train)

SVC()

In [34]:
svmc.score(X_test, y_test)

0.8403636363636363

In [35]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = svmc.predict(X_test)

In [36]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.91      0.87       254
           1       0.58      0.73      0.65       259
           2       0.85      0.76      0.80       257
           3       0.90      0.95      0.92       282
           4       0.93      0.89      0.91       247
           5       0.79      0.73      0.76       260
           6       0.83      0.78      0.80       244
           7       0.81      0.84      0.83       238
           8       0.88      0.85      0.86       252
           9       0.96      0.90      0.93       224
          10       0.98      0.92      0.95       233

    accuracy                           0.84      2750
   macro avg       0.85      0.84      0.84      2750
weighted avg       0.85      0.84      0.84      2750



In [37]:
print(confusion_matrix(y_test, y_pred))

[[232   7   1   1   0   0  11   1   1   0   0]
 [ 18 188   9   5   3   8   7  11   6   2   2]
 [  1  38 195   2   0   9   5   4   2   1   0]
 [  0   9   0 267   0   1   4   1   0   0   0]
 [  4   6   1   0 221   8   0   4   2   1   0]
 [  4  17  10   4   9 189   2   7  17   1   0]
 [ 15   8   4  15   0   4 190   4   1   1   2]
 [  3  16   2   0   1   5   6 201   1   2   1]
 [  0  15   5   1   3  10   2   3 213   0   0]
 [  0  10   1   1   0   3   0   8   0 201   0]
 [  1   8   1   0   0   2   3   4   0   0 214]]


In [ ]:
# MasoudKaviani.ir