In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy import stats

In [2]:
data = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')
data.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   
3  ...                         3            80                 0   
4  ...                         4            80                 1   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   
3                  8                      3               3               8   
4                  6                      3               3               2   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  
3                  7                        3                     0  
4                  2                        2                     2  

[5 rows x 35 columns]

In [3]:
data.describe()

Age    DailyRate  DistanceFromHome    Education  EmployeeCount  \
count  1470.000000  1470.000000       1470.000000  1470.000000         1470.0   
mean     36.923810   802.485714          9.192517     2.912925            1.0   
std       9.135373   403.509100          8.106864     1.024165            0.0   
min      18.000000   102.000000          1.000000     1.000000            1.0   
25%      30.000000   465.000000          2.000000     2.000000            1.0   
50%      36.000000   802.000000          7.000000     3.000000            1.0   
75%      43.000000  1157.000000         14.000000     4.000000            1.0   
max      60.000000  1499.000000         29.000000     5.000000            1.0   

       EmployeeNumber  EnvironmentSatisfaction   HourlyRate  JobInvolvement  \
count     1470.000000              1470.000000  1470.000000     1470.000000   
mean      1024.865306                 2.721769    65.891156        2.729932   
std        602.024335                 1.093082    20.329428        0.711561   
min          1.000000                 1.000000    30.000000        1.000000   
25%        491.250000                 2.000000    48.000000        2.000000   
50%       1020.500000                 3.000000    66.000000        3.000000   
75%       1555.750000                 4.000000    83.750000        3.000000   
max       2068.000000                 4.000000   100.000000        4.000000   

          JobLevel  ...  RelationshipSatisfaction  StandardHours  \
count  1470.000000  ...               1470.000000         1470.0   
mean      2.063946  ...                  2.712245           80.0   
std       1.106940  ...                  1.081209            0.0   
min       1.000000  ...                  1.000000           80.0   
25%       1.000000  ...                  2.000000           80.0   
50%       2.000000  ...                  3.000000           80.0   
75%       3.000000  ...                  4.000000           80.0   
max       5.000000  ...                  4.000000           80.0   

       StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
count       1470.000000        1470.000000            1470.000000   
mean           0.793878          11.279592               2.799320   
std            0.852077           7.780782               1.289271   
min            0.000000           0.000000               0.000000   
25%            0.000000           6.000000               2.000000   
50%            1.000000          10.000000               3.000000   
75%            1.000000          15.000000               3.000000   
max            3.000000          40.000000               6.000000   

       WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
count      1470.000000     1470.000000         1470.000000   
mean          2.761224        7.008163            4.229252   
std           0.706476        6.126525            3.623137   
min           1.000000        0.000000            0.000000   
25%           2.000000        3.000000            2.000000   
50%           3.000000        5.000000            3.000000   
75%           3.000000        9.000000            7.000000   
max           4.000000       40.000000           18.000000   

       YearsSinceLastPromotion  YearsWithCurrManager  
count              1470.000000           1470.000000  
mean                  2.187755              4.123129  
std                   3.222430              3.568136  
min                   0.000000              0.000000  
25%                   0.000000              2.000000  
50%                   1.000000              3.000000  
75%                   3.000000              7.000000  
max                  15.000000             17.000000  

[8 rows x 26 columns]

In [4]:
data.isnull().any()

Age                         False
Attrition                   False
BusinessTravel              False
DailyRate                   False
Department                  False
DistanceFromHome            False
Education                   False
EducationField              False
EmployeeCount               False
EmployeeNumber              False
EnvironmentSatisfaction     False
Gender                      False
HourlyRate                  False
JobInvolvement              False
JobLevel                    False
JobRole                     False
JobSatisfaction             False
MaritalStatus               False
MonthlyIncome               False
MonthlyRate                 False
NumCompaniesWorked          False
Over18                      False
OverTime                    False
PercentSalaryHike           False
PerformanceRating           False
RelationshipSatisfaction    False
StandardHours               False
StockOptionLevel            False
TotalWorkingYears           False
TrainingTimesL

In [5]:
data['Attrition'].value_counts()

No     1233
Yes     237
Name: Attrition, dtype: int64

In [6]:
data['JobSatisfaction'].value_counts()

4    459
3    442
1    289
2    280
Name: JobSatisfaction, dtype: int64

In [7]:
ct = pd.crosstab(data['Attrition'], data['JobSatisfaction'], margins=True)

In [8]:
ct

JobSatisfaction    1    2    3    4   All
Attrition                                
No               223  234  369  407  1233
Yes               66   46   73   52   237
All              289  280  442  459  1470

In [13]:
obs = np.append(ct.iloc[0][: -1].values, ct.iloc[1][: -1].values)

In [9]:
ct.iloc[0] / 1233

JobSatisfaction
1      0.180860
2      0.189781
3      0.299270
4      0.330089
All    1.000000
Name: No, dtype: float64

In [10]:
ct.iloc[1] / 237

JobSatisfaction
1      0.278481
2      0.194093
3      0.308017
4      0.219409
All    1.000000
Name: Yes, dtype: float64

In [11]:
ct.iloc[0][: -1]

JobSatisfaction
1    223
2    234
3    369
4    407
Name: No, dtype: int64

In [12]:
(ct.iloc[0] / 1233) - (ct.iloc[1] / 237)

JobSatisfaction
1     -0.097621
2     -0.004312
3     -0.008747
4      0.110680
All    0.000000
dtype: float64

In [14]:
obs

array([223, 234, 369, 407,  66,  46,  73,  52], dtype=int64)

In [15]:
row_sum = ct.iloc[0: 2, 4].values
row_sum

array([1233,  237], dtype=int64)

In [16]:
ct.loc['All', 'All']

1470

In [17]:
exp = []
for j in range(2):
    for val in ct.iloc[2, : -1].values:
        print(val, ' * ', row_sum[j], ' / ', ct.loc['All', 'All'], ' = ', val * row_sum[j] / ct.loc['All', 'All'])
        exp.append(val * row_sum[j] / ct.loc['All', 'All'])

289  *  1233  /  1470  =  242.4061224489796
280  *  1233  /  1470  =  234.85714285714286
442  *  1233  /  1470  =  370.7387755102041
459  *  1233  /  1470  =  384.99795918367346
289  *  237  /  1470  =  46.593877551020405
280  *  237  /  1470  =  45.142857142857146
442  *  237  /  1470  =  71.26122448979592
459  *  237  /  1470  =  74.00204081632653


In [18]:
exp

[242.4061224489796,
 234.85714285714286,
 370.7387755102041,
 384.99795918367346,
 46.593877551020405,
 45.142857142857146,
 71.26122448979592,
 74.00204081632653]

In [19]:
ct.iloc[2, : -1].values

array([289, 280, 442, 459], dtype=int64)

In [20]:
obs

array([223, 234, 369, 407,  66,  46,  73,  52], dtype=int64)

In [21]:
exp

[242.4061224489796,
 234.85714285714286,
 370.7387755102041,
 384.99795918367346,
 46.593877551020405,
 45.142857142857146,
 71.26122448979592,
 74.00204081632653]

In [22]:
((obs - exp) ** 2 / exp).sum()

17.505077010348

In [23]:
dof = (len(row_sum) - 1) * (len(ct.iloc[2, :-1].values) - 1)
dof

3

In [24]:
# Attrition vs JobSatisfaction
1 - stats.chi2.cdf(((obs - exp) ** 2 / exp).sum(), dof)

0.000556300451038716

In [25]:
# .............
ct

JobSatisfaction    1    2    3    4   All
Attrition                                
No               223  234  369  407  1233
Yes               66   46   73   52   237
All              289  280  442  459  1470

In [26]:
d = np.array([ct.iloc[0][: -1].values, ct.iloc[1][: -1].values])
d

array([[223, 234, 369, 407],
       [ 66,  46,  73,  52]], dtype=int64)

In [27]:
stats.chi2_contingency(d)

(17.505077010348,
 0.0005563004510387556,
 3,
 array([[242.40612245, 234.85714286, 370.73877551, 384.99795918],
        [ 46.59387755,  45.14285714,  71.26122449,  74.00204082]]))

In [28]:
from scipy.stats import chisquare
chisquare(d)

Power_divergenceResult(statistic=array([ 85.29065744, 126.22857143, 198.22624434, 274.56427015]), pvalue=array([2.57577384e-20, 2.74031376e-29, 5.09229443e-45, 1.14862090e-61]))

In [29]:
# Attrition and Education
ct = pd.crosstab(data['Attrition'], data['Education'], margins=True)
ct

Education    1    2    3    4   5   All
Attrition                              
No         139  238  473  340  43  1233
Yes         31   44   99   58   5   237
All        170  282  572  398  48  1470

In [30]:
d = np.array([ct.iloc[0][: -1].values, ct.iloc[1][: -1].values])
d

array([[139, 238, 473, 340,  43],
       [ 31,  44,  99,  58,   5]], dtype=int64)

In [31]:
stats.chi2_contingency(d)

(3.0739613982367193,
 0.5455253376565949,
 4,
 array([[142.59183673, 236.53469388, 479.77959184, 333.83265306,
          40.26122449],
        [ 27.40816327,  45.46530612,  92.22040816,  64.16734694,
           7.73877551]]))

In [32]:
# Masoud Kaviani