In [1]:
import pandas as pd

In [5]:
data = pd.read_csv('per.csv', encoding='utf8')
data.head()

NewsID                                              Title  \
0  843656  \nوزير علوم درجمع استادان نمونه: سن بازنشستگي ...   
1  837144  \nگردهمايي دانش‌آموختگان موسسه آموزش عالي سوره...   
2  436862  \nنتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌نور...   
3  227781  \nهمايش يكروزه آسيب شناسي مفهوم روابط عمومي در...   
4  174187  \nوضعيت اقتصادي و ميزان تحصيلات والدين از مهمت...   

                                                Body         Date       Time  \
0  \nوزير علوم در جمع استادان نمونه كشور گفت: از ...  \n138/5//09  \n0:9::18   
1  \nبه گزارش سرويس صنفي آموزشي خبرگزاري دانشجويا...  \n138/5//09  \n1:4::11   
2  \nنتايج آزمون دوره‌هاي فراگير مقاطع كارشناسي و...  \n138/3//07  \n1:0::03   
3                                                 \n  \n138/2//02  \n1:3::42   
4  \nمحمدتقي علوي يزدي، مجري اين طرح پژوهشي در اي...  \n138/1//08  \n1:1::49   

             Category  Category2  
0           \nآموزشي-   \nآموزشي  
1           \nآموزشي-   \nآموزشي  
2           \nآموزشي-   \nآموزشي  
3  \nاجتماعي-خانواده-  \nاجتماعي  
4           \nآموزشي-   \nآموزشي

In [6]:
with open('stopwords.txt', encoding='utf8') as stopwords_file:
    stopwords = stopwords_file.readlines()
stopwords = [line.replace('\n', '') for line in stopwords]
stopwords

['!',
 '"',
 '#',
 '(',
 ')',
 '*',
 ',',
 '-',
 '.',
 '/',
 ':',
 '[',
 ']',
 '«',
 '»',
 '،',
 '؛',
 '؟',
 'آباد',
 'آخ',
 'آخر',
 'آخرها',
 'آخه',
 'آدمهاست',
 'آرام',
 'آرام آرام',
 'آره',
 'آری',
 'آزادانه',
 'آسان',
 'آسیب پذیرند',
 'آشنایند',
 'آشکارا',
 'آقا',
 'آقای',
 'آقایان',
 'آمد',
 'آمدن',
 'آمده',
 'آمرانه',
 'آن',
 'آن گاه',
 'آنان',
 'آنانی',
 'آنجا',
 'آنرا',
 'آنطور',
 'آنقدر',
 'آنها',
 'آنهاست',
 'آنچنان',
 'آنچنان که',
 'آنچه',
 'آنکه',
 'آنگاه',
 'آن\u200cها',
 'آهان',
 'آهای',
 'آور',
 'آورد',
 'آوردن',
 'آورده',
 'آوه',
 'آی',
 'آیا',
 'آید',
 'آیند',
 'ا',
 'اتفاقا',
 'اثرِ',
 'اجراست',
 'احتراما',
 'احتمالا',
 'احیاناً',
 'اخیر',
 'اخیراً',
 'اری',
 'از',
 'از آن پس',
 'از جمله',
 'ازاین رو',
 'ازجمله',
 'ازش',
 'اساسا',
 'اساساً',
 'است',
 'استفاد',
 'استفاده',
 'اسلامی اند',
 'اش',
 'اشتباها',
 'اشکارا',
 'اصلا',
 'اصلاً',
 'اصولا',
 'اصولاً',
 'اعلام',
 'اغلب',
 'افزود',
 'افسوس',
 'اقل',
 'اقلیت',
 'الا',
 'الان',
 'البته',
 'البتّه',
 'الهی',
 'الی',
 '

In [7]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\kavia\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [8]:
nltk_stopwords = nltk.corpus.stopwords.words('english')
stopwords.extend(nltk_stopwords)
len(stopwords)

1495

In [9]:
import hazm
stemmer = hazm.Stemmer()

In [10]:
stemmer.stem('کتاب‌ها')

'کتاب'

In [11]:
from hazm import word_tokenize

In [12]:
dataset = pd.DataFrame(columns=('title_body', 'category'))
for index, row in data.iterrows():
    title_body = row['Title'] + ' ' + row['Body']
    title_body_tokenized = word_tokenize(title_body)
    title_body_tokenized_filtered = [w for w in title_body_tokenized if not w in stopwords]
    title_body_tokenized_filtered_stemmed = [stemmer.stem(w) for w in title_body_tokenized_filtered]
    dataset.loc[index] = {
        'title_body': ' '.join(title_body_tokenized_filtered_stemmed),
        'category': row['Category2'].replace('\n', '')
    }

In [13]:
dataset.head()

title_body category
0  وزير علو درجمع استاد نمونه سن بازنشستگي استاد ...   آموزشي
1  گردهمايي دانش‌آموختگ موسسه آموز عالي سوره برگز...   آموزشي
2  نتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌نور ن...   آموزشي
3  هماي يكروزه آسيب شناسي مفهو روابط عمومي بابلسر...  اجتماعي
4  وضعي اقتصادي ميز تحصيل والدين مهمترين عوامل مو...   آموزشي

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [15]:
vectorizer = TfidfVectorizer()
vectorizer.fit(dataset['title_body'])

TfidfVectorizer()

In [16]:
X = vectorizer.transform(dataset['title_body'])

In [17]:
X

<10999x60814 sparse matrix of type '<class 'numpy.float64'>'
	with 1785147 stored elements in Compressed Sparse Row format>

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
le = LabelEncoder()
y = le.fit_transform(dataset['category'])

In [20]:
le.classes_

array(['آموزشي', 'اجتماعي', 'اقتصادي', 'بهداشتي', 'تاريخي', 'سياسي',
       'علمي', 'فرهنگي', 'فقه و حقوق', 'مذهبي', 'ورزشي'], dtype=object)

In [21]:
len(y)

10999

In [22]:
import numpy as np
print(np.unique(dataset['category']))

['آموزشي' 'اجتماعي' 'اقتصادي' 'بهداشتي' 'تاريخي' 'سياسي' 'علمي' 'فرهنگي'
 'فقه و حقوق' 'مذهبي' 'ورزشي']


In [23]:
np.shape(X)

(10999, 60814)

In [24]:
np.shape(y)

(10999,)

In [25]:
from sklearn.ensemble import IsolationForest

In [26]:
IF = IsolationForest(contamination=0.05)
X_outlier = IF.fit_predict(X)

In [27]:
np.unique(X_outlier, return_counts=True)

(array([-1,  1]), array([  550, 10449], dtype=int64))

In [28]:
np.shape(X_outlier)

(10999,)

In [29]:
X = X[X_outlier == 1]

In [30]:
y = y[X_outlier == 1]

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [33]:
from sklearn import svm

In [34]:
svmc = svm.SVC()
svmc.fit(X_train, y_train)

SVC()

In [35]:
svmc.score(X_test, y_test)

0.8404133180252583

In [40]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = svmc.predict(X_test)

In [37]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.90      0.88       249
           1       0.62      0.68      0.65       249
           2       0.83      0.78      0.80       264
           3       0.86      0.94      0.90       255
           4       0.91      0.84      0.87       162
           5       0.79      0.77      0.78       237
           6       0.83      0.74      0.78       230
           7       0.85      0.85      0.85       258
           8       0.85      0.87      0.86       231
           9       0.94      0.92      0.93       256
          10       0.94      0.95      0.95       222

    accuracy                           0.84      2613
   macro avg       0.84      0.84      0.84      2613
weighted avg       0.84      0.84      0.84      2613



In [38]:
print(confusion_matrix(y_test, y_pred))

[[223   8   0   3   0   2   8   3   1   0   1]
 [ 10 170  18   9   3   8   8  10   5   4   4]
 [  2  27 206   3   0   6   9   6   2   3   0]
 [  1   8   1 240   0   2   2   0   0   0   1]
 [  2   6   0   0 136  11   0   3   3   1   0]
 [  1   9  10   1   5 182   2   4  23   0   0]
 [ 16   4   5  22   1   3 171   5   0   0   3]
 [  2  17   2   1   4   0   4 220   1   5   2]
 [  0   9   4   0   1  10   1   2 201   1   2]
 [  0   9   3   0   0   4   0   5   0 235   0]
 [  0   6   0   0   0   1   1   1   1   0 212]]


In [39]:
# MasoudKaviani.ir