# Numpy

کتابخانه‌ی نامپای، کتابخانه‌ایست برای کار با داده‌های ماتریسی که عموماً حجم بالایی دارند و محاسبات آن‌ها مبتنی بر جبرخطی انجام می‌شود

In [1]:
import numpy

In [2]:
vector = [1, 2, 3]

In [3]:
print(type(vector))

<class 'list'>


In [4]:
nvector = numpy.array(vector)

In [5]:
nvector.shape

(3,)

In [6]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [7]:
nmatrix = numpy.array(matrix)

In [8]:
nmatrix.shape

(3, 3)

In [9]:
j = 3
i = [1, 2, 3]
k = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
x = [
    [[1, 2, 3], [6, 2, 3], [8, 4, 2]],
    [[5, 2, 3], [6, 2, 3], [8, 4, 2]],
    [[1, 7, 3], [6, 2, 3], [8, 4, 2]],
]

In [10]:
narr = numpy.array([1, 2, 3])
narr

array([1, 2, 3])

In [11]:
numpy.resize(narr, (4, 4))

array([[1, 2, 3, 1],
       [2, 3, 1, 2],
       [3, 1, 2, 3],
       [1, 2, 3, 1]])

In [12]:
narr.resize((3, 3), refcheck=False)

In [14]:
matrix = numpy.ones((5, 4))

In [15]:
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
matrix = numpy.zeros((4, 4))
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
numpy.diag(narr)

array([1, 0, 0])

In [18]:
numpy.repeat([4, 3, 2], 5)

array([4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2])

In [19]:
m1 = numpy.ones((4, 5), int)
m1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
m2 = numpy.zeros((4, 5), int)
m2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [21]:
numpy.vstack([m1, m2])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [22]:
numpy.hstack([m1, m2])

array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]])

In [24]:
x = numpy.array([1, 2, 3])
y = numpy.array([4, 5, 5])

In [25]:
z = x * y
z

array([ 4, 10, 15])

In [26]:
x ** 2

array([1, 4, 9], dtype=int32)

In [27]:
x.dot(y)

29

In [28]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [29]:
narr.T

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [30]:
narr.astype('f')

array([[1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [31]:
narr.sum()

6

In [32]:
narr.max()

3

In [33]:
narr.min()

0

In [34]:
narr.argmax()

2

In [35]:
narr.argmin()

3

In [36]:
narr.mean()

0.6666666666666666

In [37]:
narr.std()

1.0540925533894598

In [1]:
import numpy
mr = numpy.arange(15) ** 2
mr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196], dtype=int32)

In [7]:
mr[5:19:6]

array([ 25, 121], dtype=int32)

In [41]:
mr[2]

4

In [42]:
mr[1:5]

array([ 1,  4,  9, 16], dtype=int32)

In [43]:
mr[:5]

array([ 0,  1,  4,  9, 16], dtype=int32)

In [44]:
mr[-2:]

array([169, 196], dtype=int32)

In [46]:
mr[5:12:3]

array([ 25,  64, 121], dtype=int32)

In [12]:
mr[10:0:-2]

array([100,  64,  36,  16,   4], dtype=int32)

In [47]:
mr[-10:-2:2]

array([ 25,  49,  81, 121], dtype=int32)

In [48]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [13]:
narr = numpy.array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
narr[-2:1, -2]

array([], dtype=int32)

In [51]:
narr[0:2, 1:3]

array([[2, 3],
       [0, 0]])

In [52]:
narr[::2, -1]

array([3, 0])

In [53]:
narr[::2, -1:]

array([[3],
       [0]])

In [10]:
import numpy as np
l = np.array([2, 3, 4])
l[-1:]

array([4])

In [54]:
narr[::-1, 2:]

array([[0],
       [0],
       [3]])

In [55]:
narr[narr >= 0]

array([1, 2, 3, 0, 0, 0, 0, 0, 0])

In [56]:
narr[narr >= 2]

array([2, 3])

In [57]:
narr >= 2

array([[False,  True,  True],
       [False, False, False],
       [False, False, False]])

In [58]:
marr = narr[-1]
marr

array([0, 0, 0])

In [59]:
marr[:] = 1
marr

array([1, 1, 1])

In [60]:
marr[:2] = 2
marr

array([2, 2, 1])

In [61]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [62]:
marr = narr.copy()
marr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [63]:
marr[:] = 0
marr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [64]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [1]:
import numpy
tarr = numpy.random.randint(0, 10, (4, 3))
tarr

array([[0, 8, 2],
       [2, 4, 9],
       [9, 7, 0],
       [5, 7, 8]])

In [3]:
tarr[0:2:2, -3:-1]

array([[0, 8]])

In [7]:
for row in tarr:
    for r in row:
        r = r ** 2
        print(r)

0
64
4
4
16
81
81
49
0
25
49
64


In [6]:
tarr ** 2

array([[ 0, 64,  4],
       [ 4, 16, 81],
       [81, 49,  0],
       [25, 49, 64]], dtype=int32)

In [6]:
for i, r in enumerate(tarr):
    print('index(' + str(i) + ') is ', r)

index(0) is  [1 6 4]
index(1) is  [1 8 3]
index(2) is  [0 1 4]
index(3) is  [8 7 1]


In [69]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [70]:
marr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [71]:
list(zip(narr, marr))

[(array([1, 2, 3]), array([0, 0, 0])),
 (array([0, 0, 0]), array([0, 0, 0])),
 (array([2, 2, 1]), array([0, 0, 0]))]

In [8]:
arr = [1, 4, 2, 9, 8, 6, 3]
arr = numpy.array(arr)
arr

array([1, 4, 2, 9, 8, 6, 3])

In [10]:
arr.shape[0]

7

In [73]:
len(arr) // 2

3

In [12]:
p = arr[len(arr) // 2]
p

9

In [13]:
l = []
for x in arr:
    if x < p:
        l.append(x)

In [14]:
l = [x for x in arr if x < p]
l

[1, 4, 2, 8, 6, 3]

In [15]:
type(l)

list

In [76]:
r = [x for x in arr if x > p]
r

[]

In [77]:
m = [x for x in arr if x == p]
m

[9]

In [78]:
l + m + r

[1, 4, 2, 8, 6, 3, 9]

In [79]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    arr = numpy.array(arr)
    p = arr[len(arr) // 2]
    l = [x for x in arr if x  < p]
    m = [x for x in arr if x == p]
    r = [x for x in arr if x > p]
    return quicksort(l) + m + quicksort(r)

In [80]:
h = [3, 6, 4, 1, 3, 9, 4]
quicksort(h)

[1, 3, 3, 4, 4, 6, 9]

In [81]:
# Masoud Kaviani